version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor: win/vs2019
    steps:
      - checkout
      - run: dotnet restore Datadog.Trace.sln
      - run: dotnet build Datadog.Trace.sln