version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor: win/vs2019
    steps:
      - checkout
      - run: dotnet restore Datadog.Trace.sln
      - run: dotnet build Datadog.Trace.sln

      - run: dotnet test test/Datadog.Trace.Tests.csproj
      - run: dotnet test test/Datadog.Trace.ClrProfiler.Managed.Tests.csproj