//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the GeneratePackageVersions tool. To safely
//     modify this file, edit PackageVersionsGeneratorDefinitions.json and
//     re-run the GeneratePackageVersions project in Visual Studio. See the
//     launchSettings.json for the project if you would like to run the tool
//     with the correct arguments outside of Visual Studio.

//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

namespace Datadog.Trace.ClrProfiler.IntegrationTests
{
    [SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements must be separated by blank line", Justification = "This is an auto-generated file.")]
    public class PackageVersions
    {
#if COMPREHENSIVE_TESTS
        public static readonly bool IsComprehensive = true;
#else
        public static readonly bool IsComprehensive = false;
#endif

        public static IEnumerable<object[]> MongoDB => IsComprehensive ? PackageVersionsComprehensive.MongoDB : PackageVersionsLatestMinors.MongoDB;

        public static IEnumerable<object[]> ElasticSearch6 => IsComprehensive ? PackageVersionsComprehensive.ElasticSearch6 : PackageVersionsLatestMinors.ElasticSearch6;

        public static IEnumerable<object[]> ElasticSearch5 => IsComprehensive ? PackageVersionsComprehensive.ElasticSearch5 : PackageVersionsLatestMinors.ElasticSearch5;

        public static IEnumerable<object[]> Npgsql => IsComprehensive ? PackageVersionsComprehensive.Npgsql : PackageVersionsLatestMinors.Npgsql;

        public static IEnumerable<object[]> SqlClient => IsComprehensive ? PackageVersionsComprehensive.SqlClient : PackageVersionsLatestMinors.SqlClient;

        public static IEnumerable<object[]> StackExchangeRedis => IsComprehensive ? PackageVersionsComprehensive.StackExchangeRedis : PackageVersionsLatestMinors.StackExchangeRedis;

        public static IEnumerable<object[]> ServiceStackRedis => IsComprehensive ? PackageVersionsComprehensive.ServiceStackRedis : PackageVersionsLatestMinors.ServiceStackRedis;

#if NETCOREAPP2_1
        public static IEnumerable<object[]> AspNetCoreMvc2 => IsComprehensive ? PackageVersionsComprehensive.AspNetCoreMvc2 : PackageVersionsLatestMinors.AspNetCoreMvc2;
#endif
            };
#endif

        public static IEnumerable<object[]> AmazonSqs =>

            new List<object[]>
            {
#if DEFAULT_SAMPLES
                new object[] { string.Empty },
#else
                new object[] { "3.1.0" },
                new object[] { "3.1.0.1" },
                new object[] { "3.1.0.2" },
                new object[] { "3.1.0.3" },
                new object[] { "3.1.0.4" },
                new object[] { "3.1.0.5" },
                new object[] { "3.1.0.6" },
                new object[] { "3.1.0.7" },
                new object[] { "3.1.0.8" },
                new object[] { "3.1.0.9" },
                new object[] { "3.1.0.10" },
                new object[] { "3.1.0.11" },
                new object[] { "3.1.0.12" },
                new object[] { "3.1.0.13" },
                new object[] { "3.3.0" },
                new object[] { "3.3.0.1" },
                new object[] { "3.3.0.2" },
                new object[] { "3.3.0.3" },
                new object[] { "3.3.1" },
                new object[] { "3.3.1.1" },
                new object[] { "3.3.1.2" },
                new object[] { "3.3.1.3" },
                new object[] { "3.3.1.4" },
                new object[] { "3.3.1.5" },
                new object[] { "3.3.1.6" },
                new object[] { "3.3.1.7" },
                new object[] { "3.3.1.8" },
                new object[] { "3.3.1.9" },
                new object[] { "3.3.1.10" },
                new object[] { "3.3.1.11" },
                new object[] { "3.3.1.12" },
                new object[] { "3.3.1.13" },
                new object[] { "3.3.1.14" },
                new object[] { "3.3.2" },
                new object[] { "3.3.2.1" },
                new object[] { "3.3.2.2" },
                new object[] { "3.3.2.3" },
                new object[] { "3.3.2.4" },
                new object[] { "3.3.2.5" },
                new object[] { "3.3.2.6" },
                new object[] { "3.3.2.7" },
                new object[] { "3.3.2.8" },
                new object[] { "3.3.2.9" },
                new object[] { "3.3.3" },
                new object[] { "3.3.3.1" },
                new object[] { "3.3.3.2" },
                new object[] { "3.3.3.3" },
                new object[] { "3.3.3.4" },
                new object[] { "3.3.3.5" },
                new object[] { "3.3.3.6" },
                new object[] { "3.3.3.7" },
                new object[] { "3.3.3.8" },
                new object[] { "3.3.3.9" },
                new object[] { "3.3.3.10" },
                new object[] { "3.3.3.11" },
                new object[] { "3.3.3.12" },
                new object[] { "3.3.3.13" },
                new object[] { "3.3.3.14" },
                new object[] { "3.3.3.15" },
                new object[] { "3.3.3.16" },
                new object[] { "3.3.3.17" },
                new object[] { "3.3.3.18" },
                new object[] { "3.3.3.19" },
                new object[] { "3.3.3.20" },
                new object[] { "3.3.3.21" },
                new object[] { "3.3.3.22" },
                new object[] { "3.3.3.23" },
                new object[] { "3.3.3.24" },
                new object[] { "3.3.3.25" },
                new object[] { "3.3.3.26" },
                new object[] { "3.3.3.27" },
                new object[] { "3.3.3.28" },
                new object[] { "3.3.3.29" },
                new object[] { "3.3.3.30" },
                new object[] { "3.3.3.31" },
                new object[] { "3.3.3.32" },
                new object[] { "3.3.3.33" },
                new object[] { "3.3.3.34" },
                new object[] { "3.3.3.35" },
                new object[] { "3.3.3.36" },
                new object[] { "3.3.3.37" },
                new object[] { "3.3.3.38" },
                new object[] { "3.3.3.39" },
                new object[] { "3.3.3.40" },
                new object[] { "3.3.3.41" },
                new object[] { "3.3.3.42" },
                new object[] { "3.3.3.43" },
                new object[] { "3.3.3.44" },
                new object[] { "3.3.3.45" },
                new object[] { "3.3.3.46" },
                new object[] { "3.3.3.47" },
                new object[] { "3.3.3.48" },
                new object[] { "3.3.3.49" },
                new object[] { "3.3.3.50" },
                new object[] { "3.3.3.51" },
                new object[] { "3.3.3.52" },
                new object[] { "3.3.3.53" },
                new object[] { "3.3.3.54" },
                new object[] { "3.3.3.55" },
                new object[] { "3.3.3.56" },
                new object[] { "3.3.3.57" },
                new object[] { "3.3.3.58" },
                new object[] { "3.3.3.59" },
                new object[] { "3.3.3.60" },
                new object[] { "3.3.3.61" },
                new object[] { "3.3.3.62" },
                new object[] { "3.3.100" },
                new object[] { "3.3.100.1" },
                new object[] { "3.3.100.2" },
                new object[] { "3.3.100.3" },
                new object[] { "3.3.100.4" },
                new object[] { "3.3.100.5" },
                new object[] { "3.3.100.6" },
                new object[] { "3.3.100.7" },
                new object[] { "3.3.100.8" },
                new object[] { "3.3.100.9" },
                new object[] { "3.3.100.10" },
                new object[] { "3.3.100.11" },
                new object[] { "3.3.100.12" },
                new object[] { "3.3.100.13" },
                new object[] { "3.3.100.14" },
                new object[] { "3.3.100.15" },
                new object[] { "3.3.100.16" },
                new object[] { "3.3.100.17" },
                new object[] { "3.3.100.18" },
                new object[] { "3.3.100.19" },
                new object[] { "3.3.100.20" },
                new object[] { "3.3.100.21" },
                new object[] { "3.3.100.22" },
                new object[] { "3.3.100.23" },
                new object[] { "3.3.100.24" },
                new object[] { "3.3.100.25" },
                new object[] { "3.3.100.26" },
                new object[] { "3.3.100.27" },
                new object[] { "3.3.100.28" },
                new object[] { "3.3.100.29" },
                new object[] { "3.3.100.30" },
                new object[] { "3.3.100.31" },
                new object[] { "3.3.100.32" },
                new object[] { "3.3.100.33" },
                new object[] { "3.3.100.34" },
                new object[] { "3.3.100.35" },
                new object[] { "3.3.100.36" },
                new object[] { "3.3.100.37" },
                new object[] { "3.3.100.38" },
                new object[] { "3.3.100.39" },
                new object[] { "3.3.100.40" },
                new object[] { "3.3.100.41" },
                new object[] { "3.3.100.42" },
                new object[] { "3.3.100.43" },
                new object[] { "3.3.100.44" },
                new object[] { "3.3.100.45" },
                new object[] { "3.3.100.46" },
                new object[] { "3.3.100.47" },
                new object[] { "3.3.100.48" },
                new object[] { "3.3.100.49" },
                new object[] { "3.3.100.50" },
                new object[] { "3.3.100.51" },
                new object[] { "3.3.100.52" },
                new object[] { "3.3.100.53" },
                new object[] { "3.3.100.54" },
                new object[] { "3.3.100.55" },
                new object[] { "3.3.100.56" },
                new object[] { "3.3.100.57" },
                new object[] { "3.3.100.58" },
                new object[] { "3.3.100.59" },
                new object[] { "3.3.100.60" },
                new object[] { "3.3.100.61" },
                new object[] { "3.3.100.62" },
                new object[] { "3.3.100.63" },
                new object[] { "3.3.100.64" },
                new object[] { "3.3.100.65" },
                new object[] { "3.3.101" },
                new object[] { "3.3.101.1" },
                new object[] { "3.3.101.2" },
                new object[] { "3.3.101.3" },
                new object[] { "3.3.102" },
                new object[] { "3.3.102.1" },
                new object[] { "3.3.102.2" },
                new object[] { "3.3.102.3" },
                new object[] { "3.3.102.4" },
                new object[] { "3.3.102.5" },
                new object[] { "3.3.102.6" },
                new object[] { "3.3.102.7" },
                new object[] { "3.3.102.8" },
                new object[] { "3.3.102.9" },
                new object[] { "3.3.102.10" },
                new object[] { "3.3.102.11" },
                new object[] { "3.3.102.12" },
                new object[] { "3.3.102.13" },
                new object[] { "3.3.102.14" },
                new object[] { "3.3.102.15" },
                new object[] { "3.3.102.16" },
                new object[] { "3.3.102.17" },
                new object[] { "3.3.102.18" },
                new object[] { "3.3.102.19" },
                new object[] { "3.3.102.20" },
                new object[] { "3.3.102.21" },
                new object[] { "3.3.102.22" },
                new object[] { "3.3.102.23" },
                new object[] { "3.3.102.24" },
                new object[] { "3.3.102.25" },
                new object[] { "3.3.102.26" },
                new object[] { "3.3.102.27" },
#endif
            };

    }
}
